### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by chelvinn** [RevenueMonster/RM-IOS#12]
Hi,

Currently I am facing this issue as shown in the screenshot below.

![Screenshot 2020-10-08 at 5 33 21 PM](https://user-images.githubusercontent.com/61046241/95441621-eceda200-098c-11eb-8cde-930b5c0c018a.png)

![Screenshot 2020-10-08 at 5 36 11 PM](https://user-images.githubusercontent.com/61046241/95441630-f0812900-098c-11eb-9c3c-d31a0f5d3b4a.png)

Thanks

**Comment by myussufz** [comment]
Hi shelving,

We have release new version to remove UIWebView, please use version 1.2. Thank you for your support.
